apiVersion: v1
kind: ConfigMap
metadata: 
  name: mongodb-config
immutable: false
data:
  username: admin1
  mongodb.conf: |
    storage:
      dbPath: /data/db
    security:
      authorization: enabled
    replication:
        replSetName: "rs0"